pull_request_rules:
  - name: Merge on CI success and review approval
    conditions:
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=shellcheck
    actions:
      merge:
        strict: smart
        method: squash
        strict_method: merge
        commit_message: title+body
